# thordata-go-sdk/.golangci.yml
version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - gosimple
    - gosec
    - bodyclose
    - exportloopref
    - typecheck

linters-settings:
  gosec:
    excludes:
      - G404