# thordata-go-sdk/.golangci.yml
run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - gosec
    - bodyclose

linters-settings:
  gosec:
    excludes:
      - G404
  errcheck:
    check-blank: false
    exclude-functions:
      - (*io.ReadCloser).Close
      - (*os.File).Close
      - (io.Closer).Close
      - (*net/http.Response).Body.Close
      - http.Response.Body.Close